-------------------------------------------------------------------------------
Test set: devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarroTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.700 s <<< FAILURE! -- in devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarroTest
devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarroTest.testDelete_NotFound -- Time elapsed: 0.024 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <devCodes.Zerphyis.ApiMotorsport.Infra.Exceptions.NotFoundException> but was: <java.util.concurrent.CompletionException>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3115)
	at devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarroTest.testDelete_NotFound(ServiceCarroTest.java:127)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.util.concurrent.CompletionException: devCodes.Zerphyis.ApiMotorsport.Infra.Exceptions.NotFoundException: Carro não encontrado com ID 1
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: devCodes.Zerphyis.ApiMotorsport.Infra.Exceptions.NotFoundException: Carro não encontrado com ID 1
	at devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarro.lambda$delete$6(ServiceCarro.java:74)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 6 more

devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarroTest.testUpdate_NotFound -- Time elapsed: 0.010 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <devCodes.Zerphyis.ApiMotorsport.Infra.Exceptions.NotFoundException> but was: <java.util.concurrent.CompletionException>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3115)
	at devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarroTest.testUpdate_NotFound(ServiceCarroTest.java:79)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.util.concurrent.CompletionException: devCodes.Zerphyis.ApiMotorsport.Infra.Exceptions.NotFoundException: Carro não encontrado com ID 1
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: devCodes.Zerphyis.ApiMotorsport.Infra.Exceptions.NotFoundException: Carro não encontrado com ID 1
	at devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarro.lambda$update$1(ServiceCarro.java:42)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarro.lambda$update$2(ServiceCarro.java:42)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more

devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarroTest.testFindById_NotFound -- Time elapsed: 0.010 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <devCodes.Zerphyis.ApiMotorsport.Infra.Exceptions.NotFoundException> but was: <java.util.concurrent.CompletionException>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3115)
	at devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarroTest.testFindById_NotFound(ServiceCarroTest.java:109)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.util.concurrent.CompletionException: devCodes.Zerphyis.ApiMotorsport.Infra.Exceptions.NotFoundException: Carro não encontrado com ID 1
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: devCodes.Zerphyis.ApiMotorsport.Infra.Exceptions.NotFoundException: Carro não encontrado com ID 1
	at devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarro.lambda$findById$4(ServiceCarro.java:65)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at devCodes.Zerphyis.ApiMotorsport.Application.Services.ServiceCarro.lambda$findById$5(ServiceCarro.java:65)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more

